### ISSUE TITLE
Project: To-Do List

### ISSUE THREAD

**Issue by NabuTech** [NabuTech/blog#14]
# To-Do List

Below are list of tasks and enhancements to complete

1. ** Feature: Home Page
- [ ] Re-structure InfoCard Components
- [ ] Update Articles List
- [ ] Create a snapshot of blog in the articles list
- [ ] Complete Styling

2. ** Feature: Footer
- [ ] Update styling

3. ** Feature: Blog Post Page
- [ ] Implement Page
- [ ] Implement CSS
- [ ] Apply logic to showing blog posts

4. ** Check Responsive Styling
- [ ]

5. **Deployment
- [ ]

6. ** Documentation
- [ ] Update Readme with Live Link
